BigSchool/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BigSchool.Models
{
    public class Course
    {
        public int Id { get; set; }
        public bool IsCanceled { get; set; }
        public ApplicationUser Lecturer { get; set; }
        [Required]
        public string LecturerId { get; set; }
        [Required]
        [StringLength(255)]
        public string Place { get; set;}
        public DateTime DateTime { get; set; }
        public Category Category { get; set; }
        [Required]
        public byte CategoryId { get; set; }

    }
    
}

BigSchool/ViewModels/CourseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using BigSchool.Models;

namespace BigSchool.ViewModels
{
    public class CourseViewModel
    {
        [Required]
        public int Id { get; set; }
        public string Place { get; set; }
         [Required]
         [FutureDate]
        public string Date { get; set; }
        [Required]
        [ValidTime]
        public string Time { get; set; }
        [Required]
        public byte Category { get; set; }
        public IEnumerable<Category> Categories { get; set; }
        public string Heading { get; set; }

        public string Action
        {
            get { return (Id != 0) ? "Update" : "Create"; }
        }
        public bool ShowAction { get; set; }
        public IQueryable<Course> UpcommingCourses { get; internal set; }

        public DateTime GetDateTime()
        {
            return DateTime.Parse(string.Format("{0} {1}", Date, Time));
        }
    }
}

BigSchool/Controllers/Api/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using BigSchool.Models;
using Microsoft.AspNet.Identity;

namespace BigSchool.Controllers.Api
{
    public class CoursesController : ApiController
    {
        public ApplicationDbContext _dbContext { get; set; }

        public CoursesController()
        {
            _dbContext = new ApplicationDbContext();
        }

        [HttpDelete]
        public IHttpActionResult Cancel(int id)
        {
            var userId = User.Identity.GetUserId();
            var course = _dbContext.Courses.Single(c => c.Id == id && c.LecturerId == userId);
            if (course.IsCanceled)
                return NotFound();
            course.IsCanceled = true;
            _dbContext.SaveChanges();
            return Ok();
        }
    }
}

BigSchool/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BigSchool.Models;
using BigSchool.ViewModels;
using Microsoft.AspNet.Identity;

namespace BigSchool.Controllers
{
    public class CourseController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public CourseController()
        {
            _dbContext = new ApplicationDbContext();
        }
        public ActionResult Create()
        {
            var viewModel = new CourseViewModel
            {
                Categories = _dbContext.Categories.ToList(),
                Heading = "Add Course"
            };
            return View(viewModel);
        }
        // GET: Course
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Categories = _dbContext.Categories.ToList();
                return View("Create", viewModel);
            }
            var course = new Course
            {
                LecturerId = User.Identity.GetUserId(),
                DateTime = viewModel.GetDateTime(),
                CategoryId = viewModel.Category,
                Place = viewModel.Place
            };
            _dbContext.Courses.Add(course);
            _dbContext.SaveChanges();

            return RedirectToAction("Index","Home");
        }

        [Authorize]
        public ActionResult Attending()
        {
            var userId = User.Identity.GetUserId();
            var courses = _dbContext.Attendances
                .Where(a => a.AttendeeId == userId)
                .Select(a => a.Course)
                .Include(l => l.Lecturer)
                .Include(l => l.Category)
                .ToList();
            var viewModel = new CoursesViewModel()
            {
                UpcommingCourses = courses,
                ShowAction = User.Identity.IsAuthenticated
            };
            return View(viewModel);
        }

        [Authorize]
        public ActionResult Mine()
        {
            var userId = User.Identity.GetUserId();
            var courses = _dbContext.Courses
                .Where(c => c.LecturerId == userId && c.DateTime > DateTime.Now)
                .Include(l => l.Lecturer)
                .Include(c => c.Category)
                .ToList();
            return View(courses);
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            var userId = User.Identity.GetUserId();
            var course = _dbContext.Courses.Single(c => c.Id == id && c.LecturerId == userId);

            var viewModel = new CourseViewModel()
            {
                Categories = _dbContext.Categories.ToList(),
                Date = course.DateTime.ToString("dd/M/yyyy"),
                Time = course.DateTime.ToString("HH:mm"),
                Category = course.CategoryId,
                Place = course.Place,
                Heading = "Edit Course",
                Id = course.Id
            };
            return View("Create", viewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(CourseViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Categories = _dbContext.Categories.ToList();
                return View("Create", viewModel);
            }

            var userId = User.Identity.GetUserId();
            var course = _dbContext.Courses.Single(c => c.Id == viewModel.Id && c.LecturerId == userId);

            course.Place = viewModel.Place;
            course.DateTime = viewModel.GetDateTime();
            course.CategoryId = viewModel.Category;
            _dbContext.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        
    }
}

BigSchool/Views/Course/Attending.cshtml
@model BigSchool.ViewModels.CoursesViewModel
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Attending</h1>
<ul class="course">
    @foreach (var course in Model.UpcommingCourses)
    {
        <li>
            <div class="date">
                <div class="month">
                    @course.DateTime.ToString("MM")
                </div>
                <div class="day">
                    @course.DateTime.ToString("dd")
                </div>
            </div>
            <div class="details">
                <span class="lecturer">
                    @course.Lecturer.Name
                    @if (Model.ShowAction)
                    {
                        <button class="btn btn-default btn-sm js-toggle-follow" data-user-id="@course.Lecturer">Follow</button>
                    }

                </span>
                <span class="category">
                    @course.Category.Name
                </span>
                @if (Model.ShowAction)
                {
                    <button data-course-id="@course.Id" class="btn btn-default btn-sm js-toggle-attendance">Going</button>
                }

            </div>
        </li>
    }
</ul>
@section scripts
{
    <script>
        $(document).ready(function() {
            $(".js-toggle-attendance").click(function(e) {
                var button = $(e.target);
                $.post("/api/attendances", { courseId: button.attr("data-course-id") })
                    .done(function() {
                        button
                            .removeClass("btn-default")
                            .addClassRules("btn-info")
                            .text("Going");
                    })
                    .fail(function() {
                        alert("Something failed");
                    });
            });
        });
        $(".js-toggle-follow").click(function(e) {
            {
                var button = $(e.target);
                $.post("/api/followings", { followeeId: button.attr("data-user-id") })
                    .done(function() {
                        button.text("Following");
                    })
                    .fail(function() {
                        alert("Something failed");
                    });
            }
        });
    </script>
}

BigSchool/Views/Course/Attending1.cshtml
@model BigSchool.ViewModels.CoursesViewModel
@{
    ViewBag.Title = "Attending";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Attending</h2>

<ul class="course">
    @foreach (var course in Model.UpcommingCourses)
    {
        <li>
            <div class="date">
                <div class="month">
                    @course.DateTime.ToString("MM")
                </div>
                <div class="day">
                    @course.DateTime.ToString("dd")
                </div>
            </div>
            <div class="details">
                <span class="lecture">
                    @course.Lecturer.Name

                    @if (Model.ShowAction)
                    {
                        <button class="btn btn-default btn-sm js-toggle-follow" data-user-id="@course.LecturerId">Follow?</button>
                    }
                </span>
                <span class="category">
                    @course.Category.Name
                </span>
                @if (Model.ShowAction)
                {
                    <button data-course-id="@course.Id" class="btn btn-default btn-sm js-toggle-attendance">Going???</button>
                }

            </div>
        </li>
    }
</ul>

BigSchool/Views/Course/Create.cshtml
@model BigSchool.ViewModels.CourseViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
@using(Html.BeginForm(Model.Action, "Course"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.Id)
    <form>
    <div class="form-group">
        @Html.LabelFor(m => m.Place)
        @Html.TextBoxFor(m => m.Place, new {@class = "form-control"})
        @Html.ValidationMessageFor(m=>m.Place)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, new {@class = "form-control"})
        @Html.ValidationMessageFor(m=>m.Date)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Time)
        @Html.TextBoxFor(m => m.Time, new {@class = "form-control"})
        @Html.ValidationMessageFor(m=>m.Time)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Category)
        @Html.DropDownListFor(m => m.Category,
            new SelectList(Model.Categories, "Id", "Name"), "", new {@class = "form-control"})
        @Html.ValidationMessageFor(m=>m.Category)
    </div>
    <button type="submit" value="Save" class="btn btn-primary">Save</button>
    @section scripts
    {
        @Scripts.Render("~/bundles/jqueryval");
    }
</form>
}

BigSchool/Views/Course/Mine.cshtml
@model IEnumerable<BigSchool.Models.Course>
@{
    ViewBag.Title = "Mine";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mine</h2>

<ul class="course">
    @foreach (var course in Model)
    {
        <li>
            <div class="date">
                <div class="month">
                    @course.DateTime.ToString("MM")
                </div>
                <div class="day">
                    @course.DateTime.ToString("dd")
                </div>
            </div>
            <div class="details">
                <span class="lecturer">
                    @course.Lecturer.Name
                </span>
                <span class="category">
                    @course.Category.Name
                </span>
            </div>
            <div class="action">
                <a href="@Url.Action("Edit", "Courses", new {id = course.Id})">
                    Edit
                </a>
                <a href="#" class="js-cancel-course" data-course-id="@course.Id">
                    Cancel
                </a>
            </div>
        </li>
    }
    
    
</ul>
@section scripts
{
    <script>
        $(document).ready(function() {
            $(".js-cancel-course").click(function(e) {
                e.preventDefault();
                var link = $(e.target);
                bootbox.confirm("Are you sure to cancel?",
                    function() {
                        $.ajax({
                                url: "/api/courses" + link.Attr("data-course-id"),
                                method: "DELETE"
                            })
                            .done(function() {
                                link.parent("li").fadeOut(function() {
                                    $(this).remove();
                                });
                            })
                            .fail(function() {
                                alert("Something failed!");
                            });
                    });
            });
        });
    </script>
}